#arithmertic operation 


In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
varadd= var + 3
print(varadd)

[4 5 6 7]


In [3]:
var = np.array([1,2,3,4])
var2= np.array([5,6,7,8])
print(var+var2)

[ 6  8 10 12]


In [4]:
var = np.array([4,5,6,6])
print(var-4)

[0 1 2 2]


In [5]:
var = np.array([3,4,5,6])
varadd = var*7
print(varadd)

[21 28 35 42]


In [6]:
var = np.array([2,4,5,6])
varadd = var/6
print(varadd)

[0.33333333 0.66666667 0.83333333 1.        ]


In [7]:
var = np.array([3,4,5,678])
varadd= var%6
print(varadd)

[3 4 5 0]


In [8]:
var = np.array([1,2,3,4])
var2= np.array([5,6,7,8])
varadd = np.add(var,var2)
print(varadd)

[ 6  8 10 12]


#2D

In [10]:
var22= np.array([[2,3,4,5,5], [2,3,4,5,6]])
var23= np.array([[5,6,7,8,9], [3,5,6,7,8]])
print(var22)
print()
print(var23)
np.add(var22,var23)

[[2 3 4 5 5]
 [2 3 4 5 6]]

[[5 6 7 8 9]
 [3 5 6 7 8]]


array([[ 7,  9, 11, 13, 14],
       [ 5,  8, 10, 12, 14]])

In [12]:
var = np.array([3,4,5,678])
varadd= np.reciprocal(var)
print(varadd)

[0 0 0 0]
