In [1]:
import numpy as np

In [5]:
var = np.array([2,34,5,6])
print("min:", np.min(var), np.argmin(var))
print("max:", np.max(var), np.argmax(var))
print("sqrt:", np.sqrt(var))

min: 2 0
max: 34 1
sqrt: [1.41421356 5.83095189 2.23606798 2.44948974]


In [13]:
var = np.array([[2,3,4,5], [3,4,5,6]])
print(np.min(var, axis=1))
print(np.max(var, axis=0))
print(np.cos(var))
print()
print(np.sin(var))
print()
print(np.cumsum(var))

[2 3]
[3 4 5 6]
[[-0.41614684 -0.9899925  -0.65364362  0.28366219]
 [-0.9899925  -0.65364362  0.28366219  0.96017029]]

[[ 0.90929743  0.14112001 -0.7568025  -0.95892427]
 [ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]]

[ 2  5  9 14 17 21 26 32]
