###zeros

In [5]:
import numpy as np 

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


empty array

In [8]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


range heading

In [10]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [11]:
#Diagonal 

ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_dia = np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [13]:
#LinSpace
ar_lin = np.linspace(1,10, num=5)
print(ar_lin)


[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
ar_lin = np.linspace(0,10, num=5)
print(ar_lin)


[ 0.   2.5  5.   7.5 10. ]


In [15]:
ar_lin = np.linspace(0,20, num=5)
print(ar_lin)


[ 0.  5. 10. 15. 20.]
