In [1]:
import numpy as np

In [7]:

var = np.array([2,3,4,5])
print(var.shape)
print(var)
print()
var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print()
print(np.add(var, var2))

(4,)
[2 3 4 5]

(3, 1)
[[1]
 [2]
 [3]]

[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [10]:
x= np.array([[1],[2]])
print(x.shape)

y= np.array([[1,2,3],[3,4,5]])
print()
print(y.shape)
print()

print(x+y)

(2, 1)

(2, 3)

[[2 3 4]
 [5 6 7]]
