In [1]:
import numpy as np

In [3]:
var = np.array([1,2,3])
print("data type :" , var.dtype)

data type : int64


In [4]:
var = np.array([1.2, 3.4, 4.2])
print("data type:" , var.dtype)

data type: float64


In [5]:
var = np.array(["robin"])
print("data type:", var.dtype) 

data type: <U5


In [7]:
x= np.array([1,2,3,4])

print("data type:" ,x.dtype) 
print(x)

data type: int64
[1 2 3 4]


In [9]:
x= np.array([1,2,3,4])

print("data type:" ,x.dtype) 
print(x)

data type: int64
[1 2 3 4]


In [10]:
x2= np.array([1,2,3,4])
new = np.float32(x2)
print("data type:" ,x2.dtype)
print("data type:", new.dtype)
print(x2)
print(new)

data type: int64
data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [11]:
x3= np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
