In [1]:
import numpy as np

In [3]:
var = np.array([1,2,3,4,4,5,6,67,67])
print(var)
print()
for i in var:
    print(i)

[ 1  2  3  4  4  5  6 67 67]

1
2
3
4
4
5
6
67
67


In [11]:
var = np.array([[2,3,4,5,6,7,7],[3,4,5,6,7,8,7]])
print(var)
print(var.shape)
print(var.ndim)
print()
for i in var:
    print(i)

    print()
for k in var:
    for l in k:
        print(l)

[[2 3 4 5 6 7 7]
 [3 4 5 6 7 8 7]]
(2, 7)
2

[2 3 4 5 6 7 7]

[3 4 5 6 7 8 7]

2
3
4
5
6
7
7
3
4
5
6
7
8
7


In [16]:
var= np.array([[[2,3,4,5,6],[1,2,3,4,4]]])
print(var.ndim)
print()
for i in var:
    for j in i:
        for k in j:
            print(k)

3

2
3
4
5
6
1
2
3
4
4


In [18]:
var= np.array([[[2,3,4,5,6],[1,2,3,4,4]]])
print(var.ndim)
print()
for i in np.nditer(var, flags=['buffered'], op_dtypes=["S"]):
    print(i)

3

np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'4')


In [20]:
var= np.array([[[2,3,4,5,6],[1,2,3,4,4]]])
print(var.ndim)
print()
for i , d in np.ndenumerate(var):
    print(i,d)

3

(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 4
(0, 0, 3) 5
(0, 0, 4) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 1, 4) 4
