In [4]:
import numpy as np

In [6]:
var= np.array([2,3,4,5])
var1=np.array([2,5,6,7])

ar= np.concatenate((var, var1))
print(ar)

[2 3 4 5 2 5 6 7]


In [8]:
var = np.array([[2,3,4,5], [3,4,5,6]])
var1 =np.array([[4,5,6,7],[6,7,8,9]])
ar= np.concatenate((var,var1),axis=1)
print(ar)

[[2 3 4 5 4 5 6 7]
 [3 4 5 6 6 7 8 9]]


In [9]:
var= np.array([2,3,4,5])
var1=np.array([2,5,6,7])

ar= np.stack((var,var1), axis=1)
ar2= np.hstack((var,var1)) #row
ar3 = np.vstack((var,var)) #column
ar4= np.dstack((var,var1)) #height
print()
print(ar)
print()
print(ar2)
print()
print(ar3)
print()
print(ar4)


[[2 2]
 [3 5]
 [4 6]
 [5 7]]

[2 3 4 5 2 5 6 7]

[[2 3 4 5]
 [2 3 4 5]]

[[[2 2]
  [3 5]
  [4 6]
  [5 7]]]


##split array

In [12]:
var= np.array([2,3,4,5])
var1=np.array([2,5,6,7])

ar= np.array_split(var, 2)
print(ar)
print(type(ar))

[array([2, 3]), array([4, 5])]
<class 'list'>
