In [2]:
#random 

#rand() heading one dimension


import numpy as np
var =np.random.rand(4)
print(var)

[0.64978973 0.34934946 0.13338157 0.47171113]


In [3]:
var1 = np.random.rand(2,4)
print(var1)

[[0.86188932 0.54459319 0.56128106 0.20005576]
 [0.70450417 0.36342924 0.7081852  0.74968749]]


In [4]:
var2= np.random.rand(2,4,5)
print(var2)

[[[0.28506581 0.43364317 0.73855224 0.94176232 0.9220417 ]
  [0.63987689 0.91726052 0.88224178 0.45032262 0.59077523]
  [0.32463522 0.53418938 0.50050494 0.06492341 0.2306649 ]
  [0.96514601 0.34481758 0.51332638 0.80755417 0.77511363]]

 [[0.05818769 0.92389267 0.47182053 0.04161924 0.60044501]
  [0.90212153 0.36928992 0.73850219 0.36463773 0.23774938]
  [0.32416259 0.93149904 0.20565523 0.27204591 0.64978745]
  [0.04812151 0.17312083 0.98994038 0.46242543 0.06294612]]]
