In [3]:
#randn()
import numpy as np
var2 =np.random.randn(4)
print(var2)

[0.06978928 2.72905035 0.73644417 0.70312974]


In [7]:
#ranf()

var3 = np.random.ranf(6)
print(var3)

[0.03682549 0.79408716 0.00228376 0.00967317 0.54172183 0.24001104]


In [8]:
#randint() min max total
var3 = np.random.randint(2,4,6)
print(var3)

[2 2 3 3 3 3]
