In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,3,4,4,5,4,3,6,7,6,5,7])
x= np.where((arr/2)==3)
print(x)

(array([ 9, 11]),)


In [5]:
arr = np.array([1,2,3,3,4,4,5,4,3,6,7,6,5,7])
x= np.where(arr==3)
print(x)

(array([2, 3, 8]),)


In [7]:
arr = np.array([1,2,3,3,4,4,5,4,3,6,7,6,5,7])
x= np.where((arr%2)==0)
print(x)

(array([ 1,  4,  5,  7,  9, 11]),)
