In [1]:
import numpy as np 

In [5]:
var = np.array([[1,2,3,4],[2,4,5,6]])
print(var)

print(var.ndim)
print()
print(var.dtype)
print(var.shape)

[[1 2 3 4]
 [2 4 5 6]]
2

int64
(2, 4)


In [7]:
var = np.array([1,2,3,4], ndmin=3)
print(var)

print(var.ndim)
print()
print(var.dtype)
print(var.shape)

[[[1 2 3 4]]]
3

int64
(1, 1, 4)


In [10]:
#reshape
var2 = np.array([1,2,3,4,5,8])
x= var2.reshape(3,2)
print(x)

[[1 2]
 [3 4]
 [5 8]]
