In [2]:
import numpy as np

In [4]:
arr= np.array([1,2,3,3,4,5,64,3,6,4,5,3])
x= np.unique(arr)
print(x)

[ 1  2  3  4  5  6 64]


In [9]:
arr= np.array([1,2,3,3,4,5,64,3,6,4,5,3])
x= np.unique(arr, return_index= True, return_counts= True)
print(x)

x1= np.resize(arr,(4,3))
print()
print(x1)

(array([ 1,  2,  3,  4,  5,  6, 64]), array([0, 1, 2, 4, 5, 8, 6]), array([1, 1, 4, 2, 2, 1, 1]))

[[ 1  2  3]
 [ 3  4  5]
 [64  3  6]
 [ 4  5  3]]
